# Generated by Django 5.1.4 on 2025-01-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_inferior', models.FloatField(help_text='Limite inferior do túnel de preço')),
                ('limite_superior', models.FloatField(help_text='Limite superior do túnel de preço')),
                ('periodicidade', models.IntegerField(help_text='Periodicidade de checagem (em minutos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(help_text='Preço registrado do ativo')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='core.ativo')),
            ],
        ),
    ]
