# Generated by Django 5.1.4 on 2025-03-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_inferior', models.DecimalField(decimal_places=2, help_text='Limite inferior do túnel de preço', max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, help_text='Limite superior do túnel de preço', max_digits=10)),
                ('periodicidade', models.IntegerField(help_text='Periodicidade de checagem (em minutos)')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço registrado do ativo', max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='core.ativo')),
            ],
        ),
    ]
